### ISSUE TITLE
V0.6.5 Not listed in releases causing difficult pods installation

### ISSUE THREAD

**Issue by ltdan450** [yconst/YCMatrix#4]
Hi Yannis,
I'm running into some trouble installing your library via cocoapods. It seems like the latest release gitHub recognizes is 0.6.4: https://github.com/yconst/YCMatrix/releases .

**Comment by yconst** [comment]
Sorry that must have been my omission pushing without tags. I push the new tag now, is it ok?

**Comment by ltdan450** [comment]
It's working now. Thanks for the effort and contribution!

**Comment by yconst** [comment]
Thanks for reporting this
