### ISSUE TITLE
eigenValuesAndEigenVectors not working

### ISSUE THREAD

**Issue by anishchopra** [yconst/YCMatrix#5]
Created an matrix as such:

[0, 4 8, 12
 1, 5, 9, 13
 2, 6, 10, 14
 3, 7, 11, 15]

The output returned from eigenValuesAndEigenVectors is incorrect. eigenValues, however, returns the correct output.

**Comment by ArEnSc** [comment]
I second this, this does not work. let me provide an example

**Comment by yconst** [comment]
Thanks for reporting this. I never got to test the actual Eigenvectors code (as evident by the lack of unit tests on this), so I may have missed a call to LAPACK. Will try to check it.

@ArEnSc if you could provide an example it would be great (could be integrated to a unit test as well).

**Comment by yconst** [comment]
This is now working ok according to my tests. Please pay attention to the following:

1. ~~Eigenvectors appear as *rows* in the result. You'll have to transpose to get columns.~~ The command has to transpose both input and output matrices to get row-major from column major format. This is subject to improvement in a future version.
2. The method name is renamed to eigenvectorsAndEigenvalues:
3. Imaginary eigenvalues are returned as well.
